name = "DCISolver"
uuid = "bee2e536-65f6-11e9-3844-e5bb4c9c55c9"
authors = ["Abel Soares Siqueira <abel.s.siqueira@gmail.com>"]
version = "0.1.0"

[deps]
HSL = "34c5aeac-e683-54a6-a0e9-6e0fdc586c50"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
LDLFactorizations = "40e66cde-538c-5869-a4ad-c39174c6795b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SolverCore = "ff4d7338-4cf1-434d-91df-b86cb86fb843"
SolverTools = "b5612192-2639-5dc1-abfe-fbedd65fab29"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
HSL = "0.1.0, 0.2.0"
Krylov = "0.6, 0.7"
LDLFactorizations = "0.8.1"
NLPModels = "0.14, 0.15"
SolverCore = "0.1"
SolverTest = "0.1.1"
SolverTools = "0.5"
julia = "^1.3.0"

[extras]
ADNLPModels = "54578032-b7ea-4c30-94aa-7cbd1cce6c9a"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SolverTest = "4343dc35-3317-4c6e-8877-f0cc8502c90e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ADNLPModels", "Logging", "Random", "SolverTest", "Test"]
